// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outer.proto

package access

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type ReqHead struct {
	Dev                  *Device  `protobuf:"bytes,1,opt,name=dev,proto3" json:"dev,omitempty"`
	Ver                  string   `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHead) Reset()         { *m = ReqHead{} }
func (m *ReqHead) String() string { return proto.CompactTextString(m) }
func (*ReqHead) ProtoMessage()    {}
func (*ReqHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{1}
}

func (m *ReqHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHead.Unmarshal(m, b)
}
func (m *ReqHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHead.Marshal(b, m, deterministic)
}
func (m *ReqHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHead.Merge(m, src)
}
func (m *ReqHead) XXX_Size() int {
	return xxx_messageInfo_ReqHead.Size(m)
}
func (m *ReqHead) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHead.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHead proto.InternalMessageInfo

func (m *ReqHead) GetDev() *Device {
	if m != nil {
		return m.Dev
	}
	return nil
}

func (m *ReqHead) GetVer() string {
	if m != nil {
		return m.Ver
	}
	return ""
}

func (m *ReqHead) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ReqHead) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ReqHead) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReqBody struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBody) Reset()         { *m = ReqBody{} }
func (m *ReqBody) String() string { return proto.CompactTextString(m) }
func (*ReqBody) ProtoMessage()    {}
func (*ReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{2}
}

func (m *ReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBody.Unmarshal(m, b)
}
func (m *ReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBody.Marshal(b, m, deterministic)
}
func (m *ReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBody.Merge(m, src)
}
func (m *ReqBody) XXX_Size() int {
	return xxx_messageInfo_ReqBody.Size(m)
}
func (m *ReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBody proto.InternalMessageInfo

func (m *ReqBody) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ReqBody) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ReqBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PkgReqHead struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkgReqHead) Reset()         { *m = PkgReqHead{} }
func (m *PkgReqHead) String() string { return proto.CompactTextString(m) }
func (*PkgReqHead) ProtoMessage()    {}
func (*PkgReqHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{3}
}

func (m *PkgReqHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReqHead.Unmarshal(m, b)
}
func (m *PkgReqHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReqHead.Marshal(b, m, deterministic)
}
func (m *PkgReqHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReqHead.Merge(m, src)
}
func (m *PkgReqHead) XXX_Size() int {
	return xxx_messageInfo_PkgReqHead.Size(m)
}
func (m *PkgReqHead) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReqHead.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReqHead proto.InternalMessageInfo

func (m *PkgReqHead) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PkgReqBody struct {
	Head                 *ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Bodys                []*ReqBody `protobuf:"bytes,2,rep,name=bodys,proto3" json:"bodys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PkgReqBody) Reset()         { *m = PkgReqBody{} }
func (m *PkgReqBody) String() string { return proto.CompactTextString(m) }
func (*PkgReqBody) ProtoMessage()    {}
func (*PkgReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{4}
}

func (m *PkgReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReqBody.Unmarshal(m, b)
}
func (m *PkgReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReqBody.Marshal(b, m, deterministic)
}
func (m *PkgReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReqBody.Merge(m, src)
}
func (m *PkgReqBody) XXX_Size() int {
	return xxx_messageInfo_PkgReqBody.Size(m)
}
func (m *PkgReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReqBody proto.InternalMessageInfo

func (m *PkgReqBody) GetHead() *ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgReqBody) GetBodys() []*ReqBody {
	if m != nil {
		return m.Bodys
	}
	return nil
}

type PkgReq struct {
	Head                 *PkgReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body                 *PkgReqBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PkgReq) Reset()         { *m = PkgReq{} }
func (m *PkgReq) String() string { return proto.CompactTextString(m) }
func (*PkgReq) ProtoMessage()    {}
func (*PkgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{5}
}

func (m *PkgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReq.Unmarshal(m, b)
}
func (m *PkgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReq.Marshal(b, m, deterministic)
}
func (m *PkgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReq.Merge(m, src)
}
func (m *PkgReq) XXX_Size() int {
	return xxx_messageInfo_PkgReq.Size(m)
}
func (m *PkgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReq proto.InternalMessageInfo

func (m *PkgReq) GetHead() *PkgReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgReq) GetBody() *PkgReqBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "access.Device")
	proto.RegisterType((*ReqHead)(nil), "access.ReqHead")
	proto.RegisterType((*ReqBody)(nil), "access.ReqBody")
	proto.RegisterType((*PkgReqHead)(nil), "access.PkgReqHead")
	proto.RegisterType((*PkgReqBody)(nil), "access.PkgReqBody")
	proto.RegisterType((*PkgReq)(nil), "access.PkgReq")
}

func init() { proto.RegisterFile("outer.proto", fileDescriptor_c96bfb384e37eb24) }

var fileDescriptor_c96bfb384e37eb24 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x6e, 0xba, 0xd5, 0xa9, 0x68, 0x19, 0x44, 0x82, 0x88, 0x2c, 0x11, 0x4b, 0x4f,
	0x3d, 0xe8, 0x3f, 0x10, 0x0f, 0x1e, 0x25, 0x20, 0xf4, 0xba, 0xdd, 0x0c, 0x6d, 0x29, 0x6e, 0xda,
	0x4d, 0xba, 0xd2, 0xa3, 0xff, 0x5c, 0x32, 0x9b, 0x28, 0xea, 0x6d, 0x5e, 0xde, 0xbc, 0x6f, 0x66,
	0x08, 0x8c, 0xed, 0xc1, 0x53, 0x3b, 0xdf, 0xb5, 0xd6, 0x5b, 0x2c, 0xaa, 0xba, 0x26, 0xe7, 0xd4,
	0x0d, 0x14, 0xcf, 0xd4, 0x6d, 0x6a, 0x42, 0x04, 0xb1, 0x3a, 0x6c, 0x8c, 0xcc, 0xca, 0x6c, 0x76,
	0xaa, 0xb9, 0x56, 0x9f, 0x19, 0x8c, 0x34, 0xed, 0x5f, 0xa8, 0x32, 0x58, 0x42, 0x6e, 0xa8, 0x63,
	0x7b, 0xfc, 0x70, 0x3e, 0xef, 0xf3, 0xf3, 0x3e, 0xac, 0x83, 0x85, 0x13, 0xc8, 0x3b, 0x6a, 0xe5,
	0x80, 0x01, 0xa1, 0x0c, 0x2f, 0x01, 0x99, 0x97, 0xd9, 0x4c, 0xe8, 0x50, 0xe2, 0x35, 0x9c, 0xec,
	0x2a, 0xe7, 0x3e, 0x6c, 0x6b, 0xa4, 0xe0, 0xc6, 0x6f, 0x8d, 0x97, 0x30, 0xf4, 0x76, 0x4b, 0x8d,
	0x1c, 0xb2, 0xd1, 0x0b, 0xf5, 0xc6, 0x2b, 0x3c, 0x59, 0x73, 0x44, 0x09, 0x23, 0x47, 0x6d, 0x18,
	0x18, 0xb7, 0x4c, 0x12, 0xaf, 0xa0, 0x78, 0x27, 0xbf, 0xb6, 0x26, 0x4e, 0x8f, 0x2a, 0x24, 0x6a,
	0xdb, 0x78, 0x6a, 0x3c, 0x2f, 0x71, 0xa6, 0x93, 0x54, 0xb7, 0x00, 0xaf, 0xdb, 0x55, 0x3a, 0x6e,
	0x02, 0xb9, 0xa3, 0x3d, 0x53, 0x85, 0x0e, 0xa5, 0x5a, 0x24, 0x9f, 0x27, 0xdf, 0x81, 0x58, 0x53,
	0x65, 0xe2, 0xf5, 0x17, 0xe9, 0xfa, 0x18, 0xd7, 0x6c, 0xe2, 0x3d, 0x0c, 0x97, 0xd6, 0x1c, 0x9d,
	0x1c, 0x94, 0xf9, 0x9f, 0xae, 0x00, 0xd1, 0xbd, 0xab, 0x16, 0x50, 0xf4, 0x64, 0x9c, 0xfe, 0xa2,
	0x62, 0xea, 0xff, 0xd9, 0x2b, 0x82, 0xa7, 0x20, 0x42, 0x94, 0x6f, 0xfb, 0xd7, 0xc7, 0x68, 0xf6,
	0x97, 0x05, 0xff, 0xed, 0xe3, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x6a, 0xcd, 0x26, 0xea,
	0x01, 0x00, 0x00,
}
